import {env} from 'cloudflare:workers';
import {Circle,roundDate} from '@/lib/model';
const db=()=>{if(!env.DB)throw new Error("Database unavailable");return env.DB;};
const uid=()=>crypto.randomUUID();
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
async function password(p:string,salt=uid()){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},k,256);return salt+':'+Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,'0')).join('');}
function fail(s:string,status=400):never{throw Object.assign(new Error(s),{status});}
async function user(req:Request){const token=req.headers.get('cookie')?.match(/chitti_session=([^;]+)/)?.[1];if(!token)return null;return db().prepare('SELECT a.id,a.name,a.login FROM accounts a JOIN sessions s ON a.id=s.user WHERE s.token=? AND s.expires>?').bind(await hash(token),Date.now()).first<{id:string;name:string;login:string}>();}
function publicCircle(c:Circle,owner:boolean){return {...c,members:c.members.map(m=>({...m,invite:undefined,phone:owner?m.phone:''})),payments:c.payments.map(p=>({...p,reference:owner?p.reference:''}))};}
export async function GET(req:Request){try{const u=await user(req);if(!u)return Response.json({user:null,circles:[]});const rows=await db().prepare('SELECT data FROM circles').all<{data:string}>();const cs=rows.results.map(r=>JSON.parse(r.data) as Circle).filter(c=>c.owner===u.id||c.members.some(m=>m.user===u.id));return Response.json({user:u,circles:cs.map(c=>publicCircle(c,c.owner===u.id))});}catch(e){console.error(e);return Response.json({error:'Unable to load your chittis. Please retry.'},{status:503});}}
export async function POST(req:Request){try{
if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)fail('Invalid origin',403);
const b=await req.json() as Record<string,string>;const action=b.action;let u=await user(req);
if(action==='register'||action==='login'){
 const login=String(b.login||'').trim().toLowerCase();const p=String(b.password||'');if(!/^[a-z0-9+_-]{3,40}$/.test(login)||p.length<10||p.length>128)fail('Use a phone number or ID and a password of 10–128 characters.');
 const key=await hash(login+':'+(req.headers.get('cf-connecting-ip')||'local'));const now=Date.now();await db().prepare('INSERT INTO attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END, expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END').bind(key,now+900000,now,now).run();const attempt=await db().prepare('SELECT count FROM attempts WHERE key=?').bind(key).first<{count:number}>();if(attempt!.count>15)fail('Too many attempts. Try again in 15 minutes.',429);
 let account=await db().prepare('SELECT * FROM accounts WHERE login=?').bind(login).first<{id:string;name:string;password:string;login:string}>();
 if(action==='register'){if(account)fail('This ID is already registered. Sign in instead.');if(!String(b.name||'').trim())fail('Enter your name.');account={id:uid(),name:String(b.name).trim().slice(0,80),login,password:await password(p)};await db().prepare('INSERT INTO accounts (id,name,login,password) VALUES (?,?,?,?)').bind(account.id,account.name,login,account.password).run();}
 else if(!account||await password(p,account.password.split(':')[0])!==account.password)fail('Incorrect ID or password.',401);
 const token=uid()+uid();await db().prepare('INSERT INTO sessions (token,user,expires) VALUES (?,?,?)').bind(await hash(token),account!.id,Date.now()+7*86400000).run();return Response.json({ok:true},{headers:{'Set-Cookie':`chitti_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=604800`}});
}
if(!u)fail('Please sign in.',401);
if(action==='logout'){const t=req.headers.get('cookie')?.match(/chitti_session=([^;]+)/)?.[1];if(t)await db().prepare('DELETE FROM sessions WHERE token=?').bind(await hash(t)).run();return Response.json({ok:true},{headers:{'Set-Cookie':'chitti_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'}});}
if(action==='create'){
 if(!b.name||!Number.isInteger(+b.amount)||+b.amount<1||+b.amount>10000000||!Number.isInteger(+b.months)||+b.months<2||+b.months>100||!/^\d{4}-\d{2}-\d{2}$/.test(b.paymentDate)||!/^\d{4}-\d{2}-\d{2}$/.test(b.drawDate)||b.drawDate<b.paymentDate)fail('Enter a name, valid amount, 2–100 months and draw date on or after payment date.');
 const c:Circle={id:uid(),owner:u.id,name:String(b.name).slice(0,80),amount:+b.amount,months:+b.months,paymentDate:b.paymentDate,drawDate:b.drawDate,picker:'',upi:String(b.upi||'').slice(0,100),members:[{id:uid(),name:u.name,phone:u.login,user:u.id}],payments:[],draws:[],maintenance:false};await db().prepare('INSERT INTO circles (id,owner,data,version) VALUES (?,?,?,0)').bind(c.id,u.id,JSON.stringify(c)).run();return Response.json({ok:true,id:c.id});
}
const row=await db().prepare('SELECT data,version FROM circles WHERE id=?').bind(String(b.id)).first<{data:string;version:number}>();if(!row)fail('Chitti not found.',404);const c=JSON.parse(row.data) as Circle;const owner=c.owner===u.id;const me=c.members.find(m=>m.user===u!.id);
if(action!=='join'&&!owner&&!me)fail('You do not belong to this chitti.',403);if(c.maintenance&&!owner)fail('Maintenance is happening. Please wait for the update.',503);
if(['add','exclude','settings','approve','manual','invite'].includes(action)&&!owner)fail('Only the owner can do this.',403);
let extra:Record<string,unknown>={};const round=c.draws.length+1;
if(action==='join'){const member=c.members.find(m=>m.invite===b.token);if(!member||member.user)fail('This invitation is invalid or has already been used.');if(me)fail('You already belong to this chitti.');member.user=u.id;member.invite=undefined;}
else if(action==='add'){if(c.draws.length)fail('Members cannot be added after the first draw.');if(c.members.length>=c.months)fail('All member slots are filled.');if(!b.name)fail('Enter a name.');const m={id:uid(),name:String(b.name).slice(0,80),phone:String(b.phone||'').slice(0,25),invite:uid()+uid()};c.members.push(m);extra={token:m.invite,member:m.id};}
else if(action==='invite'){const m=c.members.find(m=>m.id===b.member);if(!m||m.user)fail('Member already joined or not found.');m.invite=uid()+uid();extra={token:m.invite};}
else if(action==='exclude'){const m=c.members.find(m=>m.id===b.member);if(!m)fail('Member not found.');m.excluded=m.excluded?undefined:String(b.reason||'Paused by owner').slice(0,200);}
else if(action==='settings'){if(b.name)c.name=String(b.name).slice(0,80);if(b.paymentDate){if(!/^\d{4}-\d{2}-\d{2}$/.test(b.paymentDate)||!/^\d{4}-\d{2}-\d{2}$/.test(b.drawDate)||b.drawDate<b.paymentDate)fail('Check the schedule dates.');c.paymentDate=b.paymentDate;c.drawDate=b.drawDate;}if(b.picker!==undefined){if(b.picker&&!c.members.some(m=>m.id===b.picker))fail('Invalid picker.');c.picker=b.picker;}if(b.maintenance!==undefined)c.maintenance=!!b.maintenance;if(b.upi!==undefined)c.upi=String(b.upi).slice(0,100);}
else if(action==='profile'){const m=c.members.find(m=>m.id===b.member);if(!m||(!owner&&m.user!==u.id))fail('You can only edit your own profile.',403);if(!String(b.name||'').trim())fail('Enter a name.');m.name=String(b.name).trim().slice(0,80);}
else if(action==='pay'){const m=owner?c.members.find(m=>m.id===b.member):me;if(!m)fail('Member not found.');const r=+b.round;if(!Number.isInteger(r)||r<1||r>c.months)fail('Invalid month.');if(!['UPI','Cash'].includes(b.method))fail('Choose UPI or cash.');if(b.method==='UPI'&&!String(b.reference||'').trim())fail('Enter the UPI transaction ID.');if(c.payments.some(p=>p.member===m.id&&p.round===r))fail('Payment already submitted for this month.');c.payments.push({member:m.id,round:r,method:b.method,reference:String(b.reference||'').slice(0,100),status:'review',date:new Date().toISOString()});}
else if(action==='approve'){const p=c.payments.find(p=>p.member===b.member&&p.round===+b.round);if(!p)fail('Payment not found.');if(b.reject)c.payments=c.payments.filter(x=>x!==p);else p.status='paid';}
else if(action==='draw'||action==='manual'){
 if(!owner&&me?.id!==c.picker)fail('Only the owner or the nominated picker may draw.',403);if(round>c.months)fail('This chitti has finished.');if(c.members.length!==c.months)fail('Fill all member slots before starting draws.');if(+b.round!==round)fail('Another draw was recorded. Refresh first.',409);
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});if(action==='draw'&&today<roundDate(c.drawDate,round))fail('The draw opens on its scheduled date.');
 const eligible=c.members.filter(m=>!m.excluded&&!c.draws.some(d=>d.member===m.id));if(!eligible.length)fail('No eligible members remain.');let chosen=eligible.find(m=>m.id===b.member);
 if(action==='manual'){if(!chosen||!String(b.note||'').trim())fail('Choose an eligible winner and enter the offline draw details.');}else{const limit=Math.floor(4294967296/eligible.length)*eligible.length;let n;do{n=crypto.getRandomValues(new Uint32Array(1))[0];}while(n>=limit);chosen=eligible[n%eligible.length];}
 const d={member:chosen!.id,round,amount:c.amount*c.members.length,date:new Date().toISOString(),by:u.name,manual:action==='manual',note:String(b.note||'').slice(0,500)};c.draws.push(d);extra={draw:d};
}else fail('Unknown action.');
const result=await db().prepare('UPDATE circles SET data=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(c),c.id,row.version).run();if(!result.meta.changes)fail('Someone updated this chitti. Refresh and try again.',409);return Response.json({ok:true,...extra});
}catch(e){const error=e as Error&{status?:number};if(!error.status)console.error(e);return Response.json({error:error.status?error.message:'Could not save. Please retry.'},{status:error.status||503});}}
