'use client';
import {useEffect,useState,useRef,FormEvent} from 'react';
import {ArrowUpRight,ArrowRight,Bell,CalendarDays,Check,ChevronDown,CircleHelp,Clock,Gift,Home,IndianRupee,Languages,LogOut,Plus,Settings,ShieldCheck,Sparkles,Users,Wallet,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {DrawBowl} from '@/components/draw-bowl';
import {Circle,Member,sample,roundDate} from '@/lib/model';
const money=(n:number)=>'₹'+n.toLocaleString('en-IN');
const words:Record<string,string>={'Overview':'അവലോകനം','Members':'അംഗങ്ങൾ','Payments':'പണമടവുകൾ','Live draw':'തത്സമയ നറുക്കെടുപ്പ്','History':'ചരിത്രം','Settings':'ക്രമീകരണങ്ങൾ','Your chittis':'നിങ്ങളുടെ ചിട്ടികൾ','New chitti':'പുതിയ ചിട്ടി','Invite member':'അംഗത്തെ ക്ഷണിക്കുക','Monthly contribution':'മാസത്തവണ','Chitti value':'ചിട്ടിത്തുക','Collected this month':'ഈ മാസം ലഭിച്ചത്','Members in the bowl':'നറുക്കെടുപ്പിലെ അംഗങ്ങൾ','Next payment':'അടുത്ത പണമടവ്','Next lucky draw':'അടുത്ത നറുക്കെടുപ്പ്','View all':'എല്ലാം കാണുക','Paid':'അടച്ചു','Pending':'ബാക്കി','Review':'പരിശോധനയിൽ','In the bowl':'നറുക്കെടുപ്പിൽ','Selected':'തിരഞ്ഞെടുത്തു','Paused':'ഒഴിവാക്കി','Name':'പേര്','Status':'നില','Amount':'തുക','Method':'രീതി','Actions':'നടപടികൾ','Save changes':'മാറ്റങ്ങൾ സൂക്ഷിക്കുക','Sign in':'പ്രവേശിക്കുക','Create account':'അക്കൗണ്ട് സൃഷ്ടിക്കുക','Sign out':'പുറത്തുകടക്കുക','Payment reminder':'പണമടവ് ഓർമ്മപ്പെടുത്തൽ','Record payment':'പണമടവ് രേഖപ്പെടുത്തുക','Pick a paper':'ഒരു കുറി എടുക്കുക','Draw history':'നറുക്കെടുപ്പ് ചരിത്രം','Total contributed':'ആകെ അടച്ചത്','Amount received':'ലഭിച്ച തുക','Net cash flow':'അറ്റ പണമൊഴുക്ക്','Remaining commitment':'അടയ്ക്കാൻ ബാക്കിയുള്ളത്','All members':'എല്ലാ അംഗങ്ങളും','Welcome back':'വീണ്ടും സ്വാഗതം','Your circle, at a glance.':'നിങ്ങളുടെ ചിട്ടി, ഒറ്റനോട്ടത്തിൽ.','Owner workspace':'നടത്തിപ്പുകാരന്റെ ഇടം','Member workspace':'അംഗത്തിന്റെ ഇടം','Sign in to your circle':'നിങ്ങളുടെ ചിട്ടിയിൽ പ്രവേശിക്കുക','Phone number or member ID':'ഫോൺ നമ്പർ അല്ലെങ്കിൽ അംഗ ഐഡി','Password':'പാസ്‌വേഡ്','Full name':'പൂർണ്ണ പേര്','Chitti name':'ചിട്ടിയുടെ പേര്','Number of months / members':'മാസങ്ങൾ / അംഗങ്ങളുടെ എണ്ണം','First payment date':'ആദ്യ തവണ തീയതി','First draw date':'ആദ്യ നറുക്കെടുപ്പ് തീയതി','UPI ID (optional)':'UPI ഐഡി (വേണമെങ്കിൽ)','Choose the draw picker':'കുറി എടുക്കുന്ന അംഗം','Owner only':'നടത്തിപ്പുകാരൻ മാത്രം','Maintenance mode':'അറ്റകുറ്റപ്പണി നില','Waiting for the draw':'നറുക്കെടുപ്പിനായി കാത്തിരിക്കുന്നു','Payment submitted for review':'പണമടവ് പരിശോധനയ്ക്കായി സമർപ്പിച്ചു','Changes saved':'മാറ്റങ്ങൾ സൂക്ഷിച്ചു','This month':'ഈ മാസം','Confirm':'സ്ഥിരീകരിക്കുക','Reject':'നിരസിക്കുക','Phone number':'ഫോൺ നമ്പർ','Submit payment':'പണമടവ് സമർപ്പിക്കുക','Transaction ID':'ഇടപാട് ഐഡി','Cash':'പണം','Add member':'അംഗത്തെ ചേർക്കുക','Record an offline draw':'നേരിട്ടുള്ള നറുക്കെടുപ്പ് രേഖപ്പെടുത്തുക','Draw details':'നറുക്കെടുപ്പ് വിവരങ്ങൾ','Winner':'വിജയി','Notifications':'അറിയിപ്പുകൾ','No draws yet':'ഇതുവരെ നറുക്കെടുത്തിട്ടില്ല','View draw room':'നറുക്കെടുപ്പ് കാണുക','Your contribution':'നിങ്ങളുടെ തവണ','Payment progress':'പണമടവ് പുരോഗതി'};
export default function Page(){
const [lang,setLang]=useState('en');const t=(s:string)=>lang==='ml'?(words[s]||s):s;
const [user,setUser]=useState<{id:string;name:string}|null>(null),[circles,setCircles]=useState<Circle[]>([]),[selected,setSelected]=useState(''),[demo,setDemo]=useState(false),[loading,setLoading]=useState(true),[tab,setTab]=useState('Overview'),[modal,setModal]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[register,setRegister]=useState(false),[filter,setFilter]=useState('All members'),[paymentRound,setPaymentRound]=useState(1),[method,setMethod]=useState('UPI'),[target,setTarget]=useState(''),[invite,setInvite]=useState(''),[animating,setAnimating]=useState(false),[celebrate,setCelebrate]=useState(false),[inviteQuery,setInviteQuery]=useState<{id:string;token:string}|null>(null);
const seen=useRef('');const c=circles.find(x=>x.id===selected)||circles[0];const owner=!!c&&c.owner===user?.id;const me=c?.members.find(m=>m.user===user?.id);const round=c?Math.min(c.draws.length+1,c.months):1;const eligible=c?.members.filter(m=>!m.excluded&&!c.draws.some(d=>d.member===m.id))||[];
async function load(){try{const r=await fetch('/api/chitti',{cache:'no-store'});const j=await r.json() as {error:string;user:{id:string;name:string}|null;circles:Circle[]};if(!r.ok)throw Error(j.error);setUser(j.user);setCircles(j.circles);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{load();setLang(localStorage.getItem('chitti-language')||'en');const p=new URLSearchParams(location.search);if(p.get('join')&&p.get('token'))setInviteQuery({id:p.get('join')!,token:p.get('token')!});},[]);
useEffect(()=>{if(demo||!user)return;const timer=setInterval(load,4000);return()=>clearInterval(timer);},[demo,user?.id]);
useEffect(()=>{if(!c)return;const last=c.draws.at(-1);const key=c.id+':'+(last?.date||'ready');if(last&&seen.current.startsWith(c.id+':')&&seen.current!==key){setAnimating(true);const reveal=setTimeout(()=>{setAnimating(false);setCelebrate(true);},3400);const end=setTimeout(()=>setCelebrate(false),9400);seen.current=key;return()=>{clearTimeout(reveal);clearTimeout(end);};}seen.current=key;},[c?.id,c?.draws.length]);
useEffect(()=>{setPaymentRound(round);},[round,c?.id]);
useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
function open(name:string,id=''){setError('');setTarget(id);setModal(name);}
async function act(action:string,values:Record<string,unknown>={}){setBusy(true);setError('');try{if(demo){setNotice(lang==='ml'?'ഇത് മാതൃകയാണ്. സൂക്ഷിക്കാൻ അക്കൗണ്ട് സൃഷ്ടിക്കുക.':'This is a sample circle. Create an account to save your own chitti.');return null;}const r=await fetch('/api/chitti',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:c?.id,...values})});const j=await r.json() as {error:string;id:string;token:string};if(!r.ok)throw Error(j.error);await load();return j;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
function form(e:FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget).entries());}
async function save(e:FormEvent<HTMLFormElement>,action:string,extra:Record<string,unknown>={}){const data=form(e);const j=await act(action,{...data,...extra});if(j){setModal('');setNotice(t('Changes saved'));if(action==='create')setSelected(j.id);if(action==='add'){setInvite(location.origin+'/?join='+c.id+'&token='+j.token);setModal('invite');}}}
function sampleMode(){setDemo(true);setUser({id:'demo-owner',name:'Lakshmi'});setCircles([structuredClone(sample)]);setSelected('demo');setError('');}
const status=(m:Member)=>c.draws.some(d=>d.member===m.id)?'Selected':m.excluded?'Paused':'In the bowl';
const payStatus=(m:Member,r=paymentRound)=>{const p=c.payments.find(p=>p.member===m.id&&p.round===r);return p?p.status==='paid'?'Paid':'Review':'Pending';};
const name=(id:string)=>c?.members.find(m=>m.id===id)?.name||'Member';
const date=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString(lang==='ml'?'ml-IN':'en-IN',{day:'numeric',month:'short',year:'numeric'});
const confirmed=c?.payments.filter(p=>p.round===round&&p.status==='paid').length||0;
const nextPay=c?roundDate(c.paymentDate,round):'';const nextDraw=c?roundDate(c.drawDate,round):'';const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
const reminderSeen=useRef('');
useEffect(()=>{if(c&&me&&!demo&&!c.maintenance&&today>=nextPay&&reminderSeen.current!==c.id+round&&c.payments.every(p=>p.member!==me.id||p.round!==round)){reminderSeen.current=c.id+round;setModal('notifications');}},[c?.id,round,me?.id,today,nextPay,demo]);
const paidTotal=c?.payments.filter(p=>p.member===me?.id&&p.status==='paid').length*(c?.amount||0)||0;const received=c?.draws.filter(d=>d.member===me?.id).reduce((a,d)=>a+d.amount,0)||0;
function leave(){setDemo(false);setCircles([]);setUser(null);setSelected('');setModal('');}
const field=(label:string,key:string,type='text',value?:string|number,required=true)=><label className="field">{t(label)}<input name={key} type={type} defaultValue={value} required={required} min={type==='number'?1:undefined}/></label>;
const nav=[['Overview',Home],['Members',Users],['Payments',Wallet],['Live draw',Sparkles],['History',Clock],['Settings',Settings]] as const;
if(loading)return <div className="loading"><div className="logo">c.</div><p>Opening your circle…</p></div>;
return <div className="app"><aside className="sidebar"><a className="brand" href="/" aria-label="Chitti home"><span className="logo">c.</span><span>chitti<span className="brand-dot">.</span></span></a><div className="workspace-label">{t(owner?'Owner workspace':'Member workspace')}</div><div className="circle-choice"><div className="circle-icon"><Users size={19}/></div><div><b>{c?.name||'Your family circle'}</b><small>{c?`${c.members.length} ${lang==='ml'?'അംഗങ്ങൾ':'members'}`:'Together, month by month'}</small></div><ChevronDown size={16}/></div>{circles.length>1&&<select aria-label="Select chitti" value={c?.id} onChange={e=>{setSelected(e.target.value);seen.current='';}}>{circles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<nav>{nav.map(([n,Icon])=><button key={n} className={tab===n?'active':''} onClick={()=>setTab(n)}><Icon size={19}/>{t(n)}{n==='Live draw'&&<span className="live-dot"/>}</button>)}</nav><button className="new-circle" onClick={()=>open(user?'create':'auth')}><Plus size={18}/>{t('New chitti')}</button><div className="sidebar-bottom"><div className="together"><span>ചിട്ടി</span><p>{lang==='ml'?'ഒരുമിച്ച്, ഓരോ മാസവും.':'A little each month.\nA lot, together.'}</p></div><button className="help" onClick={()=>open('help')}><CircleHelp size={18}/>{lang==='ml'?'ചിട്ടി എങ്ങനെ പ്രവർത്തിക്കുന്നു':'How your chitti works'}</button>{user&&<div className="account"><span className="avatar">{user.name.slice(0,1)}</span><div><b>{user.name}</b><small>{demo?'Sample account':owner?'Chitti owner':'Member'}</small></div><button aria-label="Sign out" onClick={async()=>{if(demo)leave();else if(await act('logout'))leave();}}><LogOut size={17}/></button></div>}</div></aside>
<div className="main-shell"><header className="topbar"><span>{t('Your chittis')} <span className="slash">/</span> <b>{c?.name||'Welcome'}</b></span><div className="top-actions"><button className="language" onClick={()=>{const l=lang==='en'?'ml':'en';setLang(l);localStorage.setItem('chitti-language',l);document.documentElement.lang=l;}}><Languages size={17}/>{lang==='en'?'മലയാളം':'English'}</button><button className="notification" aria-label="Notifications" onClick={()=>open('notifications')}><Bell size={19}/><i/></button>{!user&&<button className="primary small" onClick={()=>open('auth')}>{t('Sign in')}</button>}{user&&<span className="avatar small-avatar">{user.name[0]}</span>}</div></header>
<main>{demo&&<div className="demo-banner"><span><ShieldCheck size={16}/> {lang==='ml'?'മാതൃകാ ചിട്ടി • യഥാർത്ഥ പണമിടപാടുകളില്ല':'Sample circle · Explore with example data'}</span><button onClick={()=>{leave();open('auth');setRegister(true);}}>{t('Create account')} <ArrowRight size={15}/></button></div>}{error&&<div role="alert" className="error">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
{!user?<section className="welcome"><div className="eyebrow">YOUR PEOPLE. YOUR CIRCLE.</div><h1>{lang==='ml'?'ഒരുമിച്ച് തുടങ്ങാം.':'Good things grow\nin a circle.'}</h1><p>{lang==='ml'?'നിങ്ങളുടെ കുടുംബ ചിട്ടി, തവണകൾ, നറുക്കെടുപ്പുകൾ — എല്ലാം ഒരിടത്ത്.':'A home for your family chitti. Keep contributions clear, bring everyone together, and make every draw a moment to celebrate.'}</p><div className="welcome-buttons"><button className="primary" onClick={()=>{setRegister(true);open('auth');}}>{t('Create account')} <ArrowRight size={18}/></button><button className="secondary" onClick={sampleMode}>Explore sample circle</button></div><div className="welcome-cards"><article><Users/><h3>A circle you trust</h3><p>Invite your people. Give everyone their own place.</p></article><article><Wallet/><h3>Every rupee, accounted for</h3><p>Track cash and UPI contributions month by month.</p></article><article><Sparkles/><h3>A little anticipation</h3><p>Watch the lucky paper unfold, together.</p></article></div></section>:!c?<section className="welcome"><div className="eyebrow">LET’S BEGIN</div><h1>{t('Welcome back')}, {user.name}.</h1><p>Create your first chitti or join using the invitation shared by your owner.</p><button className="primary" onClick={()=>open('create')}><Plus size={18}/>{t('New chitti')}</button></section>:c.maintenance&&!owner?<section className="welcome"><Settings size={40}/><h1>Maintenance in progress</h1><p>Please wait while your chitti owner finishes the update.</p></section>:<>
<div className="page-heading"><div><div className="eyebrow">{tab==='Overview'?t('This month'):c.name.toUpperCase()} <span>•</span> {lang==='ml'?'മാസം':'MONTH'} {round} / {c.months}</div><h1>{tab==='Overview'?t('Your circle, at a glance.'):t(tab)}</h1><p>{tab==='Overview'?(lang==='ml'?'ഓരോ തവണയും, ഒരുമിച്ച് മുന്നോട്ട്.':'A little progress, from everyone. Here’s where your chitti stands.'):tab==='Members'?'Everyone stays part of the circle, even after their lucky draw.':tab==='Live draw'?'One folded paper. One happy moment. Everyone together.':tab==='Payments'?'A clear record of every monthly contribution.':tab==='History'?'Every lucky moment, kept in one place.':'Make this chitti work for your circle.'}</p></div>{owner&&<button className="primary" onClick={()=>open('add')}><Plus size={17}/>{t('Invite member')}</button>}</div>
{tab==='Overview'&&<><div className="stat-grid">{[[t('Chitti value'),money(c.amount*c.months),`${c.months} members × ${money(c.amount)}`,IndianRupee],[t('Monthly contribution'),money(c.amount),'per member / month',Wallet],[t('Collected this month'),money(confirmed*c.amount),`${confirmed} of ${c.members.length} contributions confirmed`,Check],[t('Members in the bowl'),String(eligible.length).padStart(2,'0'),`${c.draws.length} selected · ${c.members.filter(m=>m.excluded).length} paused`,Users]].map(([label,value,hint,Icon],i)=>{const I=Icon as typeof Wallet;return <article className="stat" key={i}><div className="stat-label">{label as string}<I size={18}/></div><strong>{value as string}</strong><small>{hint as string}</small></article>;})}</div>
<div className="dashboard-grid"><section className="draw-card"><div className="draw-card-top"><span className="pill light"><span className="live-dot"/>{t('Next lucky draw')}</span><span>ROUND {String(round).padStart(2,'0')}</span></div><h2>{lang==='ml'?'അടുത്ത ഭാഗ്യശാലി\nആരായിരിക്കും?':'Whose turn\nto shine?'}</h2><p>{date(nextDraw)} <span>·</span> {eligible.length} names in the bowl</p><div className="draw-card-bottom"><div><small>THIS MONTH’S POT</small><strong>{money(c.amount*c.members.length)}</strong></div><button onClick={()=>setTab('Live draw')}>{t('View draw room')} <ArrowUpRight size={18}/></button></div><div className="orb orb-one"/><div className="orb orb-two"/><div className="spark">✳</div></section><section className="panel payment-progress"><div className="section-title"><h3>{t('Payment progress')}</h3><span className="pill">{t('This month')}</span></div><div className="progress-total">{money(confirmed*c.amount)}<span> / {money(c.amount*c.members.length)}</span></div><div className="progress-track"><span style={{width:confirmed/c.members.length*100+'%'}}/></div><div className="payment-counts"><span><i className="dot teal"/>{confirmed} {t('Paid')}</span><span><i className="dot amber"/>{c.payments.filter(p=>p.round===round&&p.status==='review').length} {t('Review')}</span><span><i className="dot gray"/>{c.members.filter(m=>payStatus(m,round)==='Pending').length} {t('Pending')}</span></div><div className="due-row"><div className="calendar-box"><CalendarDays size={20}/></div><div><small>{t('Next payment')}</small><b>{date(nextPay)}</b></div><span className="pill amber-pill">{today>nextPay?'Due now':'Upcoming'}</span></div><button className="text-button" onClick={()=>setTab('Payments')}>{t('Payments')} <ArrowRight size={17}/></button></section></div>
{me&&payStatus(me,round)==='Pending'&&<div className="reminder"><span className="reminder-icon"><Bell size={20}/></span><div><b>{t('Your contribution')} · {money(c.amount)}</b><p>Due {date(nextPay)}. Selected members continue paying until the final month.</p></div><button className="secondary" onClick={()=>{setPaymentRound(round);open('pay',me.id);}}>{t('Record payment')} <ArrowRight size={16}/></button></div>}
<section className="panel"><div className="section-title"><div><h3>{t('Your circle')}</h3><p>{c.members.length} people, one shared commitment.</p></div><button className="text-button" onClick={()=>setTab('Members')}>{t('View all')} <ArrowRight size={16}/></button></div><div className="member-preview">{c.members.slice(0,6).map((m,i)=><div key={m.id}><span className={'avatar color-'+i%4}>{m.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><b>{m.name}</b><small>{t(status(m))}</small></div>)}</div></section><div className="personal-section"><h3>{lang==='ml'?'നിങ്ങളുടെ കണക്ക്':'Your personal ledger'}</h3><div className="ledger">{[['Total contributed',paidTotal],['Amount received',received],['Net cash flow',received-paidTotal],['Remaining commitment',c.amount*c.months-paidTotal]].map(([n,v])=><div key={n}><small>{t(n as string)}</small><strong>{money(v as number)}</strong></div>)}</div><p className="footnote">Net cash flow is received minus confirmed contributions; it is not investment profit. No fees or interest are included.</p></div></>}
{tab==='Members'&&<section className="panel"><div className="section-title"><h3>{c.members.length} / {c.months} {t('Members')}</h3><span className="pill">{eligible.length} {t('In the bowl')}</span></div><Table><TableHeader><TableRow>{['Name','Status','Actions'].map(n=><TableHead key={n}>{t(n)}</TableHead>)}</TableRow></TableHeader><TableBody>{c.members.map((m,i)=><TableRow key={m.id}><TableCell><div className="person"><span className={'avatar color-'+i%4}>{m.name[0]}</span><div><b>{m.name}</b><small>{m.user?'Account connected':'Invitation pending'} {owner&&m.phone?'· '+m.phone:''}</small></div></div></TableCell><TableCell><span className={'pill '+(status(m)==='Selected'?'amber-pill':'')}>{t(status(m))}</span>{m.excluded&&<small className="block">{m.excluded}</small>}</TableCell><TableCell><div className="row-actions">{(owner||m.user===user.id)&&<button onClick={()=>open('profile',m.id)}>Edit</button>}{owner&&!m.user&&<button onClick={async()=>{const j=await act('invite',{member:m.id});if(j){setInvite(location.origin+'/?join='+c.id+'&token='+j.token);open('invite');}}}>Invite</button>}{owner&&status(m)!=='Selected'&&<button onClick={()=>m.excluded?act('exclude',{member:m.id}):open('exclude',m.id)}>{m.excluded?'Restore':'Pause'}</button>}</div></TableCell></TableRow>)}</TableBody></Table><p className="footnote">Pausing affects draw eligibility only. All members still owe every monthly contribution.</p></section>}
{tab==='Payments'&&<section className="panel"><div className="section-title"><Tabs value={filter} onValueChange={setFilter}><TabsList>{['All members','Paid','Pending','Review'].map(x=><TabsTrigger key={x} value={x}>{t(x)}</TabsTrigger>)}</TabsList></Tabs><select aria-label="Payment month" value={paymentRound} onChange={e=>setPaymentRound(+e.target.value)}>{Array.from({length:c.months},(_,i)=><option key={i} value={i+1}>Month {i+1} · {date(roundDate(c.paymentDate,i+1))}</option>)}</select></div><Table><TableHeader><TableRow>{['Name','Amount','Method','Status','Actions'].map(n=><TableHead key={n}>{t(n)}</TableHead>)}</TableRow></TableHeader><TableBody>{c.members.filter(m=>filter==='All members'||payStatus(m)===filter).map(m=>{const p=c.payments.find(p=>p.member===m.id&&p.round===paymentRound);return <TableRow key={m.id}><TableCell><b>{m.name}</b></TableCell><TableCell>{money(c.amount)}</TableCell><TableCell>{p?.method||'—'}{p?.reference&&<small className="block">{p.reference}</small>}</TableCell><TableCell><span className={'pill '+(payStatus(m)==='Pending'?'neutral':payStatus(m)==='Review'?'amber-pill':'')}>{t(payStatus(m))}</span></TableCell><TableCell><div className="row-actions">{(owner||me?.id===m.id)&&!p&&<button onClick={()=>open('pay',m.id)}>{t('Record payment')}</button>}{owner&&p?.status==='review'&&<><button onClick={()=>act('approve',{member:m.id,round:paymentRound})}>{t('Confirm')}</button><button onClick={()=>act('approve',{member:m.id,round:paymentRound,reject:true})}>{t('Reject')}</button></>}{owner&&!p&&<a target="_blank" rel="noreferrer" href={'https://wa.me/'+m.phone.replace(/\D/g,'')+'?text='+encodeURIComponent(`Hi ${m.name}, your ${money(c.amount)} contribution for ${c.name}, month ${paymentRound}, is due ${roundDate(c.paymentDate,paymentRound)}. Please sign in to record your payment: ${typeof location!=='undefined'?location.origin:''}`)}>Remind ↗</a>}</div></TableCell></TableRow>;})}</TableBody></Table><p className="footnote">A UPI transaction ID or cash submission is a payment claim. Only the owner can confirm receipt.</p></section>}
{tab==='Live draw'&&<div className="draw-layout"><section className="panel draw-stage"><span className="pill">{c.draws.length===c.months?'Chitti complete':`${t('Next lucky draw')} · ${date(nextDraw)}`}</span><h2>{animating?'A little suspense…':c.draws.length?'A lucky moment, unfolded.':'A little luck. A lot of togetherness.'}</h2><DrawBowl count={eligible.length} drawing={animating} lang={lang} winner={c.draws.length?{name:name(c.draws.at(-1)!.member),amount:money(c.draws.at(-1)!.amount),round:c.draws.at(-1)!.round}:undefined}/><p>{eligible.length} {t('In the bowl')} · {c.draws.length} {t('Selected')}</p><button className="primary" disabled={busy||animating||!eligible.length||c.draws.length>=c.months||(!owner&&me?.id!==c.picker)} onClick={async()=>{if(!eligible.length)return;setCelebrate(false);setAnimating(true);if(demo){const chosen=eligible[crypto.getRandomValues(new Uint32Array(1))[0]%eligible.length];setCircles([{...c,draws:[...c.draws,{member:chosen.id,round,amount:c.amount*c.members.length,date:new Date().toISOString(),by:'Sample picker',manual:false,note:''}]}]);}else{const result=await act('draw',{round});if(!result)setAnimating(false);}}}><Sparkles size={19}/>{animating?'Unfolding…':t('Pick a paper')}</button><small className="block draw-note">Only the owner or nominated picker can start the scheduled draw. Results sync automatically.</small>{owner&&<button className="text-button" onClick={()=>open('manual')}>{t('Record an offline draw')} <ArrowUpRight size={15}/></button>}</section><div><section className="panel"><div className="section-title"><h3>{lang==='ml'?'കുറി എടുക്കുന്നയാൾ':'The lucky hand'}</h3><Sparkles size={19}/></div><div className="person"><span className="avatar color-1">{c.picker?name(c.picker)[0]:user.name[0]}</span><div><b>{c.picker?name(c.picker):'Chitti owner'}</b><small>Nominated draw picker</small></div></div>{owner&&<button className="text-button" onClick={()=>setTab('Settings')}>Change picker <ArrowRight size={15}/></button>}</section><section className="panel bowl-list"><h3>{t('In the bowl')}</h3>{eligible.map((m,i)=><div className="bowl-member" key={m.id}><span className={'avatar color-'+i%4}>{m.name[0]}</span><b>{m.name}</b><span className="dot teal"/></div>)}{!eligible.length&&<p>No eligible members remain.</p>}</section></div></div>}
{tab==='History'&&<section className="panel"><h3>{t('Draw history')}</h3>{!c.draws.length?<div className="empty"><Gift size={40}/><h3>{t('No draws yet')}</h3><p>Your first lucky moment is scheduled for {date(nextDraw)}.</p></div>:c.draws.map(d=><div className="history-row" key={d.round}><span className="history-number">{String(d.round).padStart(2,'0')}</span><div><b>{name(d.member)}</b><small>{new Date(d.date).toLocaleString()} · {d.manual?'Offline draw':'Live draw'} · {d.by}</small>{d.note&&<p>{d.note}</p>}</div><strong>{money(d.amount)}</strong></div>)}</section>}
{tab==='Settings'&&<section className="panel settings-panel">{owner?<form onSubmit={e=>save(e,'settings')}><h3>{t('Settings')}</h3>{field('Chitti name','name','text',c.name)}<div className="form-grid">{field('First payment date','paymentDate','date',c.paymentDate)}{field('First draw date','drawDate','date',c.drawDate)}</div><p className="footnote">Dates repeat monthly, using the last day for shorter months. These are the first month’s dates.</p><label className="field">{t('Choose the draw picker')}<select name="picker" defaultValue={c.picker}><option value="">{t('Owner only')}</option>{c.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{field('UPI ID (optional)','upi','text',c.upi,false)}<button className="primary" disabled={busy}>{t('Save changes')}</button><div className="maintenance-row"><div><b>{t('Maintenance mode')}</b><small>Members see a maintenance screen until you turn this off.</small></div><Switch checked={c.maintenance} onCheckedChange={v=>act('settings',{maintenance:v})}/></div></form>:<><h3>Your profile</h3><button className="secondary" onClick={()=>open('profile',me?.id)}>Edit your name</button><p>Schedules and draw settings are managed by your chitti owner.</p></>}</section>}
</>}{inviteQuery&&user&&!demo&&<div className="join-banner"><p>You have been invited to a chitti.</p><button className="primary" disabled={busy} onClick={async()=>{if(await act('join',inviteQuery)){setInviteQuery(null);history.replaceState(null,'','/');}}}>Accept invitation</button></div>}<footer><span className="footer-brand">chitti.</span><span>Made for your circle. Built on trust.</span><span><ShieldCheck size={14}/> Clear records, shared moments</span></footer></main></div>
<Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal('');}}><DialogContent className="chitti-dialog"><DialogTitle>{t(({auth:register?'Create account':'Sign in to your circle',create:'New chitti',add:'Invite member',pay:'Record payment',invite:'Invite member',manual:'Record an offline draw',exclude:'Pause draw eligibility',profile:'Edit profile',help:'How your chitti works',notifications:'Notifications'} as Record<string,string>)[modal]||'Chitti')}</DialogTitle><DialogDescription>{modal==='auth'?'Use your phone number or member ID with a password.':modal==='add'?'Add a member, then send their personal invitation on WhatsApp.':'Your circle, kept up to date.'}</DialogDescription>{error&&<p role="alert" className="error">{error}</p>}
{modal==='auth'&&<form onSubmit={async e=>{const values=form(e);const j=await act(register?'register':'login',values);if(j){setModal('');setDemo(false);}}}>{register&&field('Full name','name')}{field('Phone number or member ID','login')}{field('Password','password','password')}<small>Use at least 10 characters. Phone OTP is not enabled.</small><button className="primary full" disabled={busy}>{t(register?'Create account':'Sign in')}</button><button type="button" className="text-button" onClick={()=>setRegister(!register)}>{register?'Already a member? Sign in':'New here? Create an account'}</button></form>}
{modal==='create'&&<form onSubmit={e=>save(e,'create')}>{field('Chitti name','name') }<div className="form-grid">{field('Monthly contribution','amount','number',2000)}{field('Number of months / members','months','number',10)}</div><div className="form-grid">{field('First payment date','paymentDate','date')}{field('First draw date','drawDate','date')}</div>{field('UPI ID (optional)','upi','text','',false)}<button className="primary full" disabled={busy}>{t('New chitti')}</button></form>}
{modal==='add'&&<form onSubmit={e=>save(e,'add')}>{field('Full name','name')}{field('Phone number','phone','tel','',false)}<p className="footnote">Include country code for WhatsApp, for example 91. Add all members before the first draw.</p><button className="primary full" disabled={busy}>{t('Add member')}</button></form>}
{modal==='invite'&&<><p>This single-use link lets one member join. Send it only to that person.</p><input readOnly value={invite} aria-label="Invitation link"/><a className="primary full" target="_blank" rel="noreferrer" href={'https://wa.me/?text='+encodeURIComponent(`Join our ${c?.name} on Chitti: ${invite}`)}>Send with WhatsApp <ArrowUpRight size={18}/></a><button className="secondary" onClick={async()=>{await navigator.clipboard.writeText(invite);setNotice('Invitation copied');}}>Copy invitation</button></>}
{modal==='pay'&&<form onSubmit={e=>save(e,'pay',{member:target,round:paymentRound,method})}><div className="payment-summary"><b>{name(target)}</b><strong>{money(c.amount)}</strong><span>Month {paymentRound}</span></div><Tabs value={method} onValueChange={setMethod}><TabsList><TabsTrigger value="UPI">UPI</TabsTrigger><TabsTrigger value="Cash">{t('Cash')}</TabsTrigger></TabsList></Tabs>{method==='UPI'?<>{c.upi&&<a className="text-button" href={`upi://pay?pa=${encodeURIComponent(c.upi)}&pn=${encodeURIComponent(c.name)}&am=${c.amount}&cu=INR`}>Open UPI app ↗</a>}{!c.upi&&<p className="footnote">Ask the owner for their UPI details before paying.</p>}{field('Transaction ID','reference')}</>:<p>Submit after handing the cash to your chitti owner.</p>}<p className="footnote">The owner will verify this payment. Recording a transaction does not transfer money.</p><button className="primary full" disabled={busy}>{t('Submit payment')}</button></form>}
{modal==='manual'&&<form onSubmit={e=>save(e,'manual',{round})}><label className="field">{t('Winner')}<select name="member" required>{eligible.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{field('Draw details','note')}<p className="footnote">Record the date, picker and reason for drawing offline. This result cannot be undone and removes the winner from future draws.</p><button className="primary full" disabled={busy}>Record confirmed result</button></form>}
{modal==='exclude'&&<form onSubmit={e=>save(e,'exclude',{member:target})}>{field('Reason','reason')}<p>Only draw eligibility changes. Monthly payments remain due.</p><button className="primary full" disabled={busy}>Pause {name(target)}</button></form>}
{modal==='profile'&&<form onSubmit={e=>save(e,'profile',{member:target})}>{field('Full name','name','text',name(target))}<button className="primary full" disabled={busy}>{t('Save changes')}</button></form>}
{modal==='notifications'&&<div>{c?<><div className="notification-item"><Wallet/><div><b>{t('Next payment')} · {money(c.amount)}</b><p>{date(nextPay)} · {me?t(payStatus(me,round)):'All members'}</p></div></div><div className="notification-item"><Sparkles/><div><b>{t('Next lucky draw')}</b><p>{date(nextDraw)} · Month {round}</p></div></div>{me&&payStatus(me,round)==='Pending'&&<button className="primary" onClick={()=>{setPaymentRound(round);open('pay',me.id);}}>{t('Record payment')}</button>}<p className="footnote">Reminders appear here while using the app. Automated SMS, WhatsApp and background push notifications are not connected.</p></>:<p>Sign in to see your reminders.</p>}</div>}
{modal==='help'&&<div className="help-copy"><p>Each member contributes the same amount every month. One eligible member receives the monthly pot.</p><p>Winners leave the draw bowl, but keep paying until the chitti ends. Pausing someone also leaves their payment commitment unchanged.</p><p>The owner confirms payment claims and appoints a draw picker. Offline draws can be recorded with a note.</p><p>All amounts shown exclude fees and interest. A draw records the award; the owner handles the actual payout separately.</p></div>}
</DialogContent></Dialog>{notice&&<div role="status" className="toast"><Check size={18}/>{notice}</div>}{celebrate&&<div className="confetti" aria-hidden="true">{Array.from({length:45},(_,i)=><i key={i} style={{left:i*2.3+'%',background:['#dca446','#19877b','#ec7658'][i%3],animationDelay:(i%8)*.15+'s',transform:`rotate(${i*23}deg)`}}/>)}</div>}</div>;
}
